// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe("Player App suite", function() {
    var compile, ctrl, elem, rootScope;
    rootScope = {};
    compile = null;
    ctrl = {};
    elem = null;
    describe("Player App controller", function() {
      return it("contains spec with an expectation", function() {
        return expect(true).toBe(true);
      });
    });
    return describe("Player App controller", function() {
      beforeEach(module("playerApp"));
      /* beforeEach inject ($rootScope, $controller, $compile) ->
          scope = $rootScope.$new()
          playerModel = PlayerModel null
          elem = angular.element('<player></player>')
          $compile(elem)($rootScope)
          ctrl = angular.element.controller "playerController", {$scope: scope, playerModel: playerModel, $timeout: {}}
      */

      /* beforeEach inject ($rootScope, $controller, $timeout, $compile) ->
        scope = $rootScope
        elem = $compile('<player></player>')(scope)
      
        playerModel = PlayerModel null
      
        console.log "html -> ", elem.html()
        ctrl = $controller "PlayerController", {$scope: scope, playerModel: playerModel, $timeout: {}}
      */

      beforeEach(inject(function($rootScope, $compile, $timeout) {
        rootScope = $rootScope;
        compile = $compile;
        return ctrl = angular.element.controller("playerController", {
          $scope: rootScope,
          playerModel: playerModel,
          $timeout: {}
        });
      }));
      it("should have  rangeslider rendered", function() {
        console.log(ctrl);
        return expect(elem.html()).toContain("slider");
      });
      xit("should have rangeslider rendered", function() {
        return expect(true).toBe(true);
      });
      return xit("should gave start set to zero", function() {
        return expect(scope.start).toBe(0);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=playerSpec.map
*/
